/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/gears anim.glb')
  const { actions } = useAnimations(animations, group)

  console.log(props);
  useEffect(() => {
    if (actions && props.isAnimationsActive) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }else{
      Object.values(actions).forEach((action) => {
        action.stop();
      });
    }
  }, [props.isAnimationsActive]);

  return (
    <group ref={group} {...props} dispose={null} scale={20} position={[0,0,-2.5]}>
      <group name="Scene" position={[0,0,0]}>
        <mesh
          name="pGear1"
          geometry={nodes.pGear1.geometry}
          material={materials.lambert1}
          position={[-0.04, 0.002, 0.129]}
          userData={{ name: 'pGear1' }}
        />
        <mesh
          name="pGear2"
          geometry={nodes.pGear2.geometry}
          material={materials.lambert1}
          position={[-0.063, 0.002, 0.13]}
          userData={{ name: 'pGear2' }}
        />
        <mesh
          name="pGear3"
          geometry={nodes.pGear3.geometry}
          material={materials.lambert1}
          position={[-0.08, 0.002, 0.13]}
          userData={{ name: 'pGear3' }}
        />
        <mesh
          name="pGear4"
          geometry={nodes.pGear4.geometry}
          material={materials.lambert1}
          position={[-0.097, 0.002, 0.13]}
          userData={{ name: 'pGear4' }}
        />
        <mesh
          name="pGear5"
          geometry={nodes.pGear5.geometry}
          material={materials.lambert1}
          position={[-0.094, -0.035, 0.13]}
          userData={{ name: 'pGear5' }}>
          <mesh
            name="pCylinder26"
            geometry={nodes.pCylinder26.geometry}
            material={materials.lambert1}
            position={[0.094, 0.035, -0.13]}
            userData={{ name: 'pCylinder26' }}
          />
          <mesh
            name="pCylinder29"
            geometry={nodes.pCylinder29.geometry}
            material={materials.lambert1}
            position={[0.094, 0.035, -0.13]}
            userData={{ name: 'pCylinder29' }}
          />
        </mesh>
        <mesh
          name="pGear6"
          geometry={nodes.pGear6.geometry}
          material={materials.lambert1}
          position={[-0.04, 0.002, 0.119]}
          userData={{ name: 'pGear6' }}
        />
        <mesh
          name="pGear7"
          geometry={nodes.pGear7.geometry}
          material={materials.lambert1}
          position={[-0.044, -0.033, 0.125]}
          userData={{ name: 'pGear7' }}
        />
        <mesh
          name="pCylinder30"
          geometry={nodes.pCylinder30.geometry}
          material={materials.lambert1}
          position={[-0.022, 0.006, 0.126]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.217}
          userData={{ name: 'pCylinder30' }}
        />
        <mesh
          name="pCylinder31"
          geometry={nodes.pCylinder31.geometry}
          material={materials.lambert1}
          position={[-0.022, -0.012, 0.127]}
          rotation={[-Math.PI, 0, 0]}
          scale={[0.056, 1.691, 0.056]}
          userData={{ name: 'pCylinder31' }}
        />
        <mesh
          name="pCylinder32"
          geometry={nodes.pCylinder32.geometry}
          material={materials.lambert1}
          position={[-0.022, -0.049, 0.143]}
          scale={[1.343, 0.04, 1.343]}
          userData={{ name: 'pCylinder32' }}>
          <mesh
            name="pCube1"
            geometry={nodes.pCube1.geometry}
            material={materials.lambert1}
            position={[-0.005, 0.167, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube1' }}
          />
          <mesh
            name="pCube2"
            geometry={nodes.pCube2.geometry}
            material={materials.lambert1}
            position={[0.005, 0.167, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube2' }}
          />
          <mesh
            name="pCube3"
            geometry={nodes.pCube3.geometry}
            material={materials.lambert1}
            position={[0.005, 0.315, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube3' }}
          />
          <mesh
            name="pCube4"
            geometry={nodes.pCube4.geometry}
            material={materials.lambert1}
            position={[-0.005, 0.315, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube4' }}
          />
          <mesh
            name="pCube5"
            geometry={nodes.pCube5.geometry}
            material={materials.lambert1}
            position={[0.005, 0.46, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube5' }}
          />
          <mesh
            name="pCube6"
            geometry={nodes.pCube6.geometry}
            material={materials.lambert1}
            position={[-0.005, 0.46, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube6' }}
          />
          <mesh
            name="pCube7"
            geometry={nodes.pCube7.geometry}
            material={materials.lambert1}
            position={[0, 0.609, 0.006]}
            scale={[0.898, 29.815, 0.898]}
            userData={{ name: 'pCube7' }}
          />
        </mesh>
        <mesh
          name="pCylinder33"
          geometry={nodes.pCylinder33.geometry}
          material={materials.lambert1}
          position={[-0.004, 0.002, 0.133]}
          rotation={[0, 0, 0.141]}
          scale={0.699}
          userData={{ name: 'pCylinder33' }}
        />
        <mesh
          name="pCylinder34"
          geometry={nodes.pCylinder34.geometry}
          material={materials.lambert1}
          position={[-0.058, -0.05, 0.123]}
          rotation={[1.727, -0.143, -0.297]}
          scale={[0.092, 0.157, 0.092]}
          userData={{ name: 'pCylinder34' }}>
          <mesh
            name="pCube8"
            geometry={nodes.pCube8.geometry}
            material={materials.lambert1}
            position={[0.004, -0.003, -0.179]}
            rotation={[-Math.PI / 2, 0, -0.057]}
            scale={[2.982, 2.982, 0.45]}
            userData={{ name: 'pCube8' }}
          />
          <mesh
            name="pCube9"
            geometry={nodes.pCube9.geometry}
            material={materials.lambert1}
            position={[0.163, 0.002, -0.075]}
            rotation={[Math.PI / 2, 0, -2.005]}
            scale={[2.982, 2.982, 0.45]}
            userData={{ name: 'pCube9' }}
          />
          <mesh
            name="pCylinder35"
            geometry={nodes.pCylinder35.geometry}
            material={materials.lambert1}
            scale={[1.239, 0.651, 1.239]}
            userData={{ name: 'pCylinder35' }}
          />
        </mesh>
        <mesh
          name="pCylinder36"
          geometry={nodes.pCylinder36.geometry}
          material={materials.lambert1}
          position={[-0.061, -0.028, 0.121]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.194, 0.775, 0.194]}
          userData={{ name: 'pCylinder36' }}
        />
        <mesh
          name="pCube10"
          geometry={nodes.pCube10.geometry}
          material={materials.lambert1}
          position={[-0.003, -0.01, 0.116]}
          scale={[21.557, 15.344, 0.48]}
          userData={{ name: 'pCube10' }}
        />
        <mesh
          name="pCylinder37"
          geometry={nodes.pCylinder37.geometry}
          material={materials.lambert1}
          position={[0.017, -0.006, 0.127]}
          rotation={[0, 0, -0.347]}
          scale={[0.329, 0.977, 0.329]}
          userData={{ name: 'pCylinder37' }}
        />
        <mesh
          name="pCube11"
          geometry={nodes.pCube11.geometry}
          material={materials.lambert1}
          position={[-0.003, -0.083, 0.121]}
          scale={[21.557, 0.77, 0.48]}
          userData={{ name: 'pCube11' }}
        />
        <mesh
          name="pCylinder41"
          geometry={nodes.pCylinder41.geometry}
          material={materials.lambert1}
          position={[0, 0, -0.027]}
          userData={{ name: 'pCylinder41' }}
        />
        <mesh
          name="pCylinder42"
          geometry={nodes.pCylinder42.geometry}
          material={materials.lambert1}
          position={[0.093, 0.059, 0.122]}
          userData={{ name: 'pCylinder42' }}
        />
        <mesh
          name="pCylinder43"
          geometry={nodes.pCylinder43.geometry}
          material={materials.lambert1}
          position={[0.028, 0.059, 0.122]}
          userData={{ name: 'pCylinder43' }}
        />
        <mesh
          name="pCylinder44"
          geometry={nodes.pCylinder44.geometry}
          material={materials.lambert1}
          position={[-0.038, 0.059, 0.122]}
          userData={{ name: 'pCylinder44' }}
        />
        <mesh
          name="pCylinder45"
          geometry={nodes.pCylinder45.geometry}
          material={materials.lambert1}
          position={[-0.102, 0.059, 0.123]}
          userData={{ name: 'pCylinder45' }}
        />
        <mesh
          name="pCylinder48"
          geometry={nodes.pCylinder48.geometry}
          material={materials.lambert1}
          userData={{ name: 'pCylinder48' }}
        />
        <mesh
          name="pCylinder49"
          geometry={nodes.pCylinder49.geometry}
          material={materials.lambert1}
          position={[-0.161, -0.042, 0.002]}
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: 'pCylinder49' }}
        />
        <mesh
          name="pCylinder50"
          geometry={nodes.pCylinder50.geometry}
          material={materials.lambert1}
          position={[-0.102, -0.07, 0.122]}
          userData={{ name: 'pCylinder50' }}
        />
        <mesh
          name="pCylinder51"
          geometry={nodes.pCylinder51.geometry}
          material={materials.lambert1}
          position={[-0.064, -0.07, 0.122]}
          userData={{ name: 'pCylinder51' }}
        />
        <mesh
          name="pCylinder52"
          geometry={nodes.pCylinder52.geometry}
          material={materials.lambert1}
          position={[-0.021, -0.07, 0.122]}
          userData={{ name: 'pCylinder52' }}
        />
        <mesh
          name="pCylinder53"
          geometry={nodes.pCylinder53.geometry}
          material={materials.lambert1}
          position={[0.022, -0.07, 0.122]}
          userData={{ name: 'pCylinder53' }}
        />
        <mesh
          name="pCylinder54"
          geometry={nodes.pCylinder54.geometry}
          material={materials.lambert1}
          position={[-0.074, -0.011, 0]}
          rotation={[0, 0, -Math.PI]}
          userData={{ name: 'pCylinder54' }}
        />
        <mesh
          name="pCylinder55"
          geometry={nodes.pCylinder55.geometry}
          material={materials.lambert1}
          position={[0.013, -0.016, 0.127]}
          rotation={[0, 0, -0.354]}
          scale={[0.073, 0.151, 0.073]}
          userData={{ name: 'pCylinder55' }}
        />
        <mesh
          name="pCylinder56"
          geometry={nodes.pCylinder56.geometry}
          material={materials.lambert1}
          position={[-0.042, -0.06, 0.135]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.194, 0.775, 0.194]}
          userData={{ name: 'pCylinder56' }}
        />
        <mesh
          name="pCylinder57"
          geometry={nodes.pCylinder57.geometry}
          material={materials.lambert1}
          position={[0.021, -0.059, 0.125]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.194, 0.775, 0.194]}
          userData={{ name: 'pCylinder57' }}
        />
        <mesh
          name="pCube12"
          geometry={nodes.pCube12.geometry}
          material={materials.lambert1}
          position={[-0.06, -0.032, 0.122]}
          rotation={[0, 0, -1.014]}
          scale={[1, 0.078, 0.209]}
          userData={{ name: 'pCube12' }}
        />
        <mesh
          name="pCylinder58"
          geometry={nodes.pCylinder58.geometry}
          material={materials.lambert1}
          position={[-0.083, 0.036, 0.134]}
          rotation={[0, 0, 0.416]}
          scale={1.097}
          userData={{ name: 'pCylinder58' }}
        />
        <mesh
          name="pCube13"
          geometry={nodes.pCube13.geometry}
          material={materials.lambert1}
          position={[-0.088, 0.045, 0.122]}
          scale={[0.789, 1.713, 0.149]}
          userData={{ name: 'pCube13' }}
        />
        <mesh
          name="pCube14"
          geometry={nodes.pCube14.geometry}
          material={materials.lambert1}
          position={[-0.088, 0.045, 0.119]}
          scale={[0.789, 1.447, 0.121]}
          userData={{ name: 'pCube14' }}
        />
        <mesh
          name="pCylinder59"
          geometry={nodes.pCylinder59.geometry}
          material={materials.lambert1}
          position={[0.048, -0.049, 0.124]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.634, 0.929, 0.634]}
          userData={{ name: 'pCylinder59' }}
        />
        <mesh
          name="pCylinder60"
          geometry={nodes.pCylinder60.geometry}
          material={materials.lambert1}
          position={[0.06, -0.056, 0.124]}
          scale={0.08}
          userData={{ name: 'pCylinder60' }}
        />
        <mesh
          name="pCylinder61"
          geometry={nodes.pCylinder61.geometry}
          material={materials.lambert1}
          position={[0.061, -0.011, 0.135]}
          scale={1.653}
          userData={{ name: 'pCylinder61' }}
        />
        <mesh
          name="pCylinder62"
          geometry={nodes.pCylinder62.geometry}
          material={materials.lambert1}
          position={[0.078, -0.05, 0.126]}
          userData={{ name: 'pCylinder62' }}
        />
        <mesh
          name="pCube15"
          geometry={nodes.pCube15.geometry}
          material={materials.lambert1}
          position={[0.078, -0.071, 0.125]}
          scale={[2.827, 0.389, 1]}
          userData={{ name: 'pCube15' }}
        />
        <mesh
          name="pCube16"
          geometry={nodes.pCube16.geometry}
          material={materials.lambert1}
          position={[0.086, -0.069, 0.124]}
          scale={0.137}
          userData={{ name: 'pCube16' }}
        />
        <mesh
          name="pCube17"
          geometry={nodes.pCube17.geometry}
          material={materials.lambert1}
          position={[0.086, -0.069, 0.126]}
          scale={0.137}
          userData={{ name: 'pCube17' }}
        />
        <mesh
          name="pCylinder63"
          geometry={nodes.pCylinder63.geometry}
          material={materials.lambert1}
          position={[0.098, -0.07, 0.122]}
          userData={{ name: 'pCylinder63' }}
        />
        <mesh
          name="pCube18"
          geometry={nodes.pCube18.geometry}
          material={materials.lambert1}
          position={[0.085, -0.021, 0.123]}
          rotation={[0, 0, -0.251]}
          scale={0.651}
          userData={{ name: 'pCube18' }}>
          <mesh
            name="pCube19"
            geometry={nodes.pCube19.geometry}
            material={materials.lambert1}
            position={[-0.02, 0.069, 0]}
            rotation={[0, 0, -0.01]}
            scale={[0.459, 1.088, 0.995]}
            userData={{ name: 'pCube19' }}
          />
        </mesh>
        <mesh
          name="pSphere1"
          geometry={nodes.pSphere1.geometry}
          material={materials.lambert1}
          position={[0.06, 0.021, 0.135]}
          scale={1.469}
          userData={{ name: 'pSphere1' }}
        />
        <mesh
          name="pGear8"
          geometry={nodes.pGear8.geometry}
          material={materials.lambert1}
          position={[-0.084, 0.075, 0.116]}
          userData={{ name: 'pGear8' }}
        />
        <mesh
          name="pGear9"
          geometry={nodes.pGear9.geometry}
          material={materials.lambert1}
          position={[-0.067, 0.075, 0.116]}
          userData={{ name: 'pGear9' }}
        />
        <mesh
          name="pGear10"
          geometry={nodes.pGear10.geometry}
          material={materials.lambert1}
          position={[-0.05, 0.075, 0.116]}
          userData={{ name: 'pGear10' }}
        />
        <mesh
          name="pGear11"
          geometry={nodes.pGear11.geometry}
          material={materials.lambert1}
          position={[-0.032, 0.075, 0.116]}
          userData={{ name: 'pGear11' }}
        />
        <mesh
          name="pGear12"
          geometry={nodes.pGear12.geometry}
          material={materials.lambert1}
          position={[-0.015, 0.075, 0.116]}
          userData={{ name: 'pGear12' }}
        />
        <mesh
          name="pGear13"
          geometry={nodes.pGear13.geometry}
          material={materials.lambert1}
          position={[0.002, 0.075, 0.116]}
          userData={{ name: 'pGear13' }}
        />
        <mesh
          name="pGear14"
          geometry={nodes.pGear14.geometry}
          material={materials.lambert1}
          position={[0.019, 0.075, 0.116]}
          userData={{ name: 'pGear14' }}
        />
        <mesh
          name="pGear15"
          geometry={nodes.pGear15.geometry}
          material={materials.lambert1}
          position={[0.036, 0.075, 0.116]}
          userData={{ name: 'pGear15' }}
        />
        <mesh
          name="pGear16"
          geometry={nodes.pGear16.geometry}
          material={materials.lambert1}
          position={[0.053, 0.075, 0.116]}
          userData={{ name: 'pGear16' }}
        />
        <mesh
          name="pGear17"
          geometry={nodes.pGear17.geometry}
          material={materials.lambert1}
          position={[0.071, 0.075, 0.116]}
          userData={{ name: 'pGear17' }}
        />
        <mesh
          name="pCylinder64"
          geometry={nodes.pCylinder64.geometry}
          material={materials.lambert1}
          position={[0.052, 0.093, 0.124]}
          rotation={[-0.793, 0.699, -0.48]}
          scale={[1, 0.056, 1]}
          userData={{ name: 'pCylinder64' }}
        />
        <mesh
          name="pSphere2"
          geometry={nodes.pSphere2.geometry}
          material={materials.lambert1}
          position={[-0.074, 0.091, 0.123]}
          rotation={[0, 0, -0.758]}
          userData={{ name: 'pSphere2' }}
        />
        <mesh
          name="pCube20"
          geometry={nodes.pCube20.geometry}
          material={materials.lambert1}
          position={[-0.08, 0.077, 0.125]}
          scale={[0.722, 0.917, 0.181]}
          userData={{ name: 'pCube20' }}
        />
        <mesh
          name="pCube21"
          geometry={nodes.pCube21.geometry}
          material={materials.lambert1}
          position={[-0.08, 0.077, 0.121]}
          scale={[0.722, 0.917, 0.181]}
          userData={{ name: 'pCube21' }}
        />
        <mesh
          name="pCylinder65"
          geometry={nodes.pCylinder65.geometry}
          material={materials.lambert1}
          position={[-0.079, 0.079, 0.123]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.106, 0.282, 0.106]}
          userData={{ name: 'pCylinder65' }}
        />
        <mesh
          name="pCube22"
          geometry={nodes.pCube22.geometry}
          material={materials.lambert1}
          position={[-0.004, 0.022, 0.119]}
          scale={[4.162, 1.645, 0.169]}
          userData={{ name: 'pCube22' }}
        />
        <mesh
          name="pCube23"
          geometry={nodes.pCube23.geometry}
          material={materials.lambert1}
          position={[0.023, 0.022, 0.119]}
          scale={[0.786, 0.987, 0.169]}
          userData={{ name: 'pCube23' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/gears anim.glb')
